//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.4959
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace PVEntityGenerator.XMLSchema {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("platform-definition", Namespace="", IsNullable=false)]
    public partial class platformdefinition {
        
        private parameterdefinitionsParameterdefinition[] parameterdefinitionsField;
        
        private type_generationdefinition entitygenerationField;
        
        private string nameField;
        
        private platformdefinitionNewlinetype newlinetypeField;
        
        private bool uppercasemethodnamesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("parameter-definitions")]
        [System.Xml.Serialization.XmlArrayItemAttribute("parameter-definition", IsNullable=false)]
        public parameterdefinitionsParameterdefinition[] parameterdefinitions {
            get {
                return this.parameterdefinitionsField;
            }
            set {
                this.parameterdefinitionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entity-generation")]
        public type_generationdefinition entitygeneration {
            get {
                return this.entitygenerationField;
            }
            set {
                this.entitygenerationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("newline-type")]
        public platformdefinitionNewlinetype newlinetype {
            get {
                return this.newlinetypeField;
            }
            set {
                this.newlinetypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("uppercase-method-names")]
        public bool uppercasemethodnames {
            get {
                return this.uppercasemethodnamesField;
            }
            set {
                this.uppercasemethodnamesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class parameterdefinitionsParameterdefinition {
        
        private string nameField;
        
        private string externalnameField;
        
        private parameterdefinitionsParameterdefinitionType typeField;
        
        private string categoryField;
        
        private string descriptionField;
        
        private bool requiredField;
        
        private bool requiredFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("external-name")]
        public string externalname {
            get {
                return this.externalnameField;
            }
            set {
                this.externalnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public parameterdefinitionsParameterdefinitionType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool required {
            get {
                return this.requiredField;
            }
            set {
                this.requiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requiredSpecified {
            get {
                return this.requiredFieldSpecified;
            }
            set {
                this.requiredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum parameterdefinitionsParameterdefinitionType {
        
        /// <remarks/>
        VARCHAR,
        
        /// <remarks/>
        PASSWORD,
        
        /// <remarks/>
        PATH,
        
        /// <remarks/>
        CLOB,
        
        /// <remarks/>
        INTEGER,
        
        /// <remarks/>
        BIT,
        
        /// <remarks/>
        TIMESTAMP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class type_generation {
        
        private type_generationGenerateglobal generateglobalField;
        
        private type_generationGenerateentity[] generateentityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("generate-global")]
        public type_generationGenerateglobal generateglobal {
            get {
                return this.generateglobalField;
            }
            set {
                this.generateglobalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("generate-entity")]
        public type_generationGenerateentity[] generateentity {
            get {
                return this.generateentityField;
            }
            set {
                this.generateentityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class type_generationGenerateglobal {
        
        private parametersParameter[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("parameter", IsNullable=false)]
        public parametersParameter[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class parametersParameter {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class type_generationGenerateentity {
        
        private parametersParameter[] parametersField;
        
        private type_generationGenerateentityRemoveconstraintmessage[] removeconstraintmessagesField;
        
        private type_generationGenerateentityCustomcreatemethod[] customcreatemethodsField;
        
        private type_generationGenerateentityCustomfindmethod[] customfindmethodsField;
        
        private type_generationGenerateentityEnumerationentry[] enumerationentriesField;
        
        private string entityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("parameter", IsNullable=false)]
        public parametersParameter[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("remove-constraint-messages")]
        [System.Xml.Serialization.XmlArrayItemAttribute("remove-constraint-message", IsNullable=false)]
        public type_generationGenerateentityRemoveconstraintmessage[] removeconstraintmessages {
            get {
                return this.removeconstraintmessagesField;
            }
            set {
                this.removeconstraintmessagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("custom-create-methods")]
        [System.Xml.Serialization.XmlArrayItemAttribute("custom-create-method", IsNullable=false)]
        public type_generationGenerateentityCustomcreatemethod[] customcreatemethods {
            get {
                return this.customcreatemethodsField;
            }
            set {
                this.customcreatemethodsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("custom-find-methods")]
        [System.Xml.Serialization.XmlArrayItemAttribute("custom-find-method", IsNullable=false)]
        public type_generationGenerateentityCustomfindmethod[] customfindmethods {
            get {
                return this.customfindmethodsField;
            }
            set {
                this.customfindmethodsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("enumeration-entries")]
        [System.Xml.Serialization.XmlArrayItemAttribute("enumeration-entry", IsNullable=false)]
        public type_generationGenerateentityEnumerationentry[] enumerationentries {
            get {
                return this.enumerationentriesField;
            }
            set {
                this.enumerationentriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class type_generationGenerateentityRemoveconstraintmessage {
        
        private string foreignentityField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("foreign-entity")]
        public string foreignentity {
            get {
                return this.foreignentityField;
            }
            set {
                this.foreignentityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class type_generationGenerateentityCustomcreatemethod {
        
        private type_generationGenerateentityCustomcreatemethodMethodattribute[] methodattributeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("method-attribute")]
        public type_generationGenerateentityCustomcreatemethodMethodattribute[] methodattribute {
            get {
                return this.methodattributeField;
            }
            set {
                this.methodattributeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class type_generationGenerateentityCustomcreatemethodMethodattribute {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class type_generationGenerateentityCustomfindmethod {
        
        private type_generationGenerateentityCustomfindmethodMethodattribute[] methodattributeField;
        
        private type_generationGenerateentityCustomfindmethodInnerjoin[] innerjoinField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string entityaliasField;
        
        private string whereexpressionField;
        
        private string orderbyexpressionField;
        
        private bool returnsmultipleField;
        
        private bool generatetestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("method-attribute")]
        public type_generationGenerateentityCustomfindmethodMethodattribute[] methodattribute {
            get {
                return this.methodattributeField;
            }
            set {
                this.methodattributeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inner-join")]
        public type_generationGenerateentityCustomfindmethodInnerjoin[] innerjoin {
            get {
                return this.innerjoinField;
            }
            set {
                this.innerjoinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("entity-alias")]
        public string entityalias {
            get {
                return this.entityaliasField;
            }
            set {
                this.entityaliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("where-expression")]
        public string whereexpression {
            get {
                return this.whereexpressionField;
            }
            set {
                this.whereexpressionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("order-by-expression")]
        public string orderbyexpression {
            get {
                return this.orderbyexpressionField;
            }
            set {
                this.orderbyexpressionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("returns-multiple")]
        public bool returnsmultiple {
            get {
                return this.returnsmultipleField;
            }
            set {
                this.returnsmultipleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("generate-test")]
        public bool generatetest {
            get {
                return this.generatetestField;
            }
            set {
                this.generatetestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class type_generationGenerateentityCustomfindmethodMethodattribute {
        
        private string nameField;
        
        private type_AttributeType typeField;
        
        private bool typeFieldSpecified;
        
        private string entityaliasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public type_AttributeType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("entity-alias")]
        public string entityalias {
            get {
                return this.entityaliasField;
            }
            set {
                this.entityaliasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    public enum type_AttributeType {
        
        /// <remarks/>
        BIGINT,
        
        /// <remarks/>
        BIT,
        
        /// <remarks/>
        BYTE,
        
        /// <remarks/>
        BLOB,
        
        /// <remarks/>
        CLOB,
        
        /// <remarks/>
        DECIMAL,
        
        /// <remarks/>
        FLOAT,
        
        /// <remarks/>
        ID,
        
        /// <remarks/>
        INTEGER,
        
        /// <remarks/>
        SMALLINT,
        
        /// <remarks/>
        TIMESTAMP,
        
        /// <remarks/>
        VARCHAR,
        
        /// <remarks/>
        VSTAMP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class type_generationGenerateentityCustomfindmethodInnerjoin {
        
        private string entityField;
        
        private string entityaliasField;
        
        private string joinexpressionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("entity-alias")]
        public string entityalias {
            get {
                return this.entityaliasField;
            }
            set {
                this.entityaliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("join-expression")]
        public string joinexpression {
            get {
                return this.joinexpressionField;
            }
            set {
                this.joinexpressionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class type_generationGenerateentityEnumerationentry {
        
        private string idField;
        
        private string identifierField;
        
        private string nameField;
        
        private string descriptionField;
        
        private bool generateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool generate {
            get {
                return this.generateField;
            }
            set {
                this.generateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="type_generate-file-container")]
    public partial class type_generatefilecontainer {
        
        private parameterdefinitionsParameterdefinition[] parameterdefinitionsField;
        
        private generatefile[] generatefileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("parameter-definitions")]
        [System.Xml.Serialization.XmlArrayItemAttribute("parameter-definition", IsNullable=false)]
        public parameterdefinitionsParameterdefinition[] parameterdefinitions {
            get {
                return this.parameterdefinitionsField;
            }
            set {
                this.parameterdefinitionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("generate-file")]
        public generatefile[] generatefile {
            get {
                return this.generatefileField;
            }
            set {
                this.generatefileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("generate-file", Namespace="", IsNullable=false)]
    public partial class generatefile {
        
        private string nameField;
        
        private string pathField;
        
        private string filenameField;
        
        private string transformField;
        
        private generatefileEncoding encodingField;
        
        private bool encodingFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transform {
            get {
                return this.transformField;
            }
            set {
                this.transformField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public generatefileEncoding encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool encodingSpecified {
            get {
                return this.encodingFieldSpecified;
            }
            set {
                this.encodingFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum generatefileEncoding {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ISO-8859-1")]
        ISO88591,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("UTF-8")]
        UTF8,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="type_generation-definition")]
    public partial class type_generationdefinition {
        
        private type_generatefilecontainer generateglobalField;
        
        private type_generatefilecontainer generateentityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("generate-global")]
        public type_generatefilecontainer generateglobal {
            get {
                return this.generateglobalField;
            }
            set {
                this.generateglobalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("generate-entity")]
        public type_generatefilecontainer generateentity {
            get {
                return this.generateentityField;
            }
            set {
                this.generateentityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum platformdefinitionNewlinetype {
        
        /// <remarks/>
        WINDOWS,
        
        /// <remarks/>
        UNIX,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("db-platform-definition", Namespace="", IsNullable=false)]
    public partial class dbplatformdefinition {
        
        private parameterdefinitionsParameterdefinition[] parameterdefinitionsField;
        
        private dbplatformdefinitionDbproviderdefinition[] dbproviderdefinitionsField;
        
        private type_generationdefinition scriptgenerationField;
        
        private string nameField;
        
        private string scriptdelimiterField;
        
        private string alternativescriptdelimiterField;
        
        private bool scriptdelimiternewlineField;
        
        private string groupstatementsField;
        
        private string foreignkeychecksonField;
        
        private string foreignkeychecksoffField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("parameter-definitions")]
        [System.Xml.Serialization.XmlArrayItemAttribute("parameter-definition", IsNullable=false)]
        public parameterdefinitionsParameterdefinition[] parameterdefinitions {
            get {
                return this.parameterdefinitionsField;
            }
            set {
                this.parameterdefinitionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("db-provider-definitions")]
        [System.Xml.Serialization.XmlArrayItemAttribute("db-provider-definition", IsNullable=false)]
        public dbplatformdefinitionDbproviderdefinition[] dbproviderdefinitions {
            get {
                return this.dbproviderdefinitionsField;
            }
            set {
                this.dbproviderdefinitionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("script-generation")]
        public type_generationdefinition scriptgeneration {
            get {
                return this.scriptgenerationField;
            }
            set {
                this.scriptgenerationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("script-delimiter")]
        public string scriptdelimiter {
            get {
                return this.scriptdelimiterField;
            }
            set {
                this.scriptdelimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("alternative-script-delimiter")]
        public string alternativescriptdelimiter {
            get {
                return this.alternativescriptdelimiterField;
            }
            set {
                this.alternativescriptdelimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("script-delimiter-newline")]
        public bool scriptdelimiternewline {
            get {
                return this.scriptdelimiternewlineField;
            }
            set {
                this.scriptdelimiternewlineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("group-statements", DataType="integer")]
        public string groupstatements {
            get {
                return this.groupstatementsField;
            }
            set {
                this.groupstatementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("foreign-key-checks-on")]
        public string foreignkeycheckson {
            get {
                return this.foreignkeychecksonField;
            }
            set {
                this.foreignkeychecksonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("foreign-key-checks-off")]
        public string foreignkeychecksoff {
            get {
                return this.foreignkeychecksoffField;
            }
            set {
                this.foreignkeychecksoffField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class dbplatformdefinitionDbproviderdefinition {
        
        private parameterdefinitionsParameterdefinition[] parameterdefinitionsField;
        
        private string nameField;
        
        private dbplatformdefinitionDbproviderdefinitionType typeField;
        
        private string providerassemblyField;
        
        private string providerclassField;
        
        private string connectionstringField;
        
        private string sqlparameterprefixField;
        
        private bool trustedauthField;
        
        public dbplatformdefinitionDbproviderdefinition() {
            this.trustedauthField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("parameter-definitions")]
        [System.Xml.Serialization.XmlArrayItemAttribute("parameter-definition", IsNullable=false)]
        public parameterdefinitionsParameterdefinition[] parameterdefinitions {
            get {
                return this.parameterdefinitionsField;
            }
            set {
                this.parameterdefinitionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public dbplatformdefinitionDbproviderdefinitionType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("provider-assembly")]
        public string providerassembly {
            get {
                return this.providerassemblyField;
            }
            set {
                this.providerassemblyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("provider-class")]
        public string providerclass {
            get {
                return this.providerclassField;
            }
            set {
                this.providerclassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("connection-string")]
        public string connectionstring {
            get {
                return this.connectionstringField;
            }
            set {
                this.connectionstringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("sql-parameter-prefix")]
        public string sqlparameterprefix {
            get {
                return this.sqlparameterprefixField;
            }
            set {
                this.sqlparameterprefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("trusted-auth")]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool trustedauth {
            get {
                return this.trustedauthField;
            }
            set {
                this.trustedauthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum dbplatformdefinitionDbproviderdefinitionType {
        
        /// <remarks/>
        NET,
        
        /// <remarks/>
        OLEDB,
        
        /// <remarks/>
        ODBC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("parameter-definitions", Namespace="", IsNullable=false)]
    public partial class parameterdefinitions {
        
        private parameterdefinitionsParameterdefinition[] parameterdefinitionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameter-definition")]
        public parameterdefinitionsParameterdefinition[] parameterdefinition {
            get {
                return this.parameterdefinitionField;
            }
            set {
                this.parameterdefinitionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("pventitygenerator-config", Namespace="", IsNullable=false)]
    public partial class pventitygeneratorconfig {
        
        private pventitygeneratorconfigPlatform[] platformsField;
        
        private pventitygeneratorconfigDbplatform[] dbplatformsField;
        
        private pventitygeneratorconfigProjectdefinition projectdefinitionField;
        
        private type_generationdefinition entitygenerationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("platform", IsNullable=false)]
        public pventitygeneratorconfigPlatform[] platforms {
            get {
                return this.platformsField;
            }
            set {
                this.platformsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("db-platforms")]
        [System.Xml.Serialization.XmlArrayItemAttribute("db-platform", IsNullable=false)]
        public pventitygeneratorconfigDbplatform[] dbplatforms {
            get {
                return this.dbplatformsField;
            }
            set {
                this.dbplatformsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("project-definition")]
        public pventitygeneratorconfigProjectdefinition projectdefinition {
            get {
                return this.projectdefinitionField;
            }
            set {
                this.projectdefinitionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entity-generation")]
        public type_generationdefinition entitygeneration {
            get {
                return this.entitygenerationField;
            }
            set {
                this.entitygenerationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class pventitygeneratorconfigPlatform {
        
        private string nameField;
        
        private string definitiondirField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("definition-dir")]
        public string definitiondir {
            get {
                return this.definitiondirField;
            }
            set {
                this.definitiondirField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class pventitygeneratorconfigDbplatform {
        
        private string nameField;
        
        private string definitiondirField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("definition-dir")]
        public string definitiondir {
            get {
                return this.definitiondirField;
            }
            set {
                this.definitiondirField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class pventitygeneratorconfigProjectdefinition {
        
        private parameterdefinitionsParameterdefinition[] parameterdefinitionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("parameter-definitions")]
        [System.Xml.Serialization.XmlArrayItemAttribute("parameter-definition", IsNullable=false)]
        public parameterdefinitionsParameterdefinition[] parameterdefinitions {
            get {
                return this.parameterdefinitionsField;
            }
            set {
                this.parameterdefinitionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("project-settings", Namespace="", IsNullable=false)]
    public partial class projectsettings {
        
        private parametersParameter[] parametersField;
        
        private projectsettingsEntitygeneration entitygenerationField;
        
        private projectsettingsEntityexport entityexportField;
        
        private projectsettingsPlatforms platformsField;
        
        private projectsettingsDbplatforms dbplatformsField;
        
        private string pventitygeneratorversionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("parameter", IsNullable=false)]
        public parametersParameter[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entity-generation")]
        public projectsettingsEntitygeneration entitygeneration {
            get {
                return this.entitygenerationField;
            }
            set {
                this.entitygenerationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entity-export")]
        public projectsettingsEntityexport entityexport {
            get {
                return this.entityexportField;
            }
            set {
                this.entityexportField = value;
            }
        }
        
        /// <remarks/>
        public projectsettingsPlatforms platforms {
            get {
                return this.platformsField;
            }
            set {
                this.platformsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("db-platforms")]
        public projectsettingsDbplatforms dbplatforms {
            get {
                return this.dbplatformsField;
            }
            set {
                this.dbplatformsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("pventitygenerator-version")]
        public string pventitygeneratorversion {
            get {
                return this.pventitygeneratorversionField;
            }
            set {
                this.pventitygeneratorversionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class projectsettingsEntitygeneration : type_generation {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class projectsettingsEntityexport {
        
        private projectsettingsEntityexportExportentity[] exportentitiesField;
        
        private projectsettingsEntityexportPatchentity[] patchentitiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("export-entities")]
        [System.Xml.Serialization.XmlArrayItemAttribute("export-entity", IsNullable=false)]
        public projectsettingsEntityexportExportentity[] exportentities {
            get {
                return this.exportentitiesField;
            }
            set {
                this.exportentitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("patch-entities")]
        [System.Xml.Serialization.XmlArrayItemAttribute("patch-entity", IsNullable=false)]
        public projectsettingsEntityexportPatchentity[] patchentities {
            get {
                return this.patchentitiesField;
            }
            set {
                this.patchentitiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class projectsettingsEntityexportExportentity {
        
        private string entityField;
        
        private string sortnoField;
        
        private bool exportstructureField;
        
        private bool exportdataField;
        
        private bool exportdropField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("sort-no", DataType="integer")]
        public string sortno {
            get {
                return this.sortnoField;
            }
            set {
                this.sortnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("export-structure")]
        public bool exportstructure {
            get {
                return this.exportstructureField;
            }
            set {
                this.exportstructureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("export-data")]
        public bool exportdata {
            get {
                return this.exportdataField;
            }
            set {
                this.exportdataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("export-drop")]
        public bool exportdrop {
            get {
                return this.exportdropField;
            }
            set {
                this.exportdropField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class projectsettingsEntityexportPatchentity {
        
        private projectsettingsEntityexportPatchentityPatchattribute[] patchattributeField;
        
        private string entityField;
        
        private type_PatchType patchtypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("patch-attribute")]
        public projectsettingsEntityexportPatchentityPatchattribute[] patchattribute {
            get {
                return this.patchattributeField;
            }
            set {
                this.patchattributeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("patch-type")]
        public type_PatchType patchtype {
            get {
                return this.patchtypeField;
            }
            set {
                this.patchtypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class projectsettingsEntityexportPatchentityPatchattribute {
        
        private string nameField;
        
        private type_PatchType patchtypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("patch-type")]
        public type_PatchType patchtype {
            get {
                return this.patchtypeField;
            }
            set {
                this.patchtypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    public enum type_PatchType {
        
        /// <remarks/>
        CREATE,
        
        /// <remarks/>
        MODIFY,
        
        /// <remarks/>
        DROP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class projectsettingsPlatforms {
        
        private projectsettingsPlatformsPlatform[] platformField;
        
        private string selectedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("platform")]
        public projectsettingsPlatformsPlatform[] platform {
            get {
                return this.platformField;
            }
            set {
                this.platformField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string selected {
            get {
                return this.selectedField;
            }
            set {
                this.selectedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class projectsettingsPlatformsPlatform {
        
        private parametersParameter[] parametersField;
        
        private type_generation entitygenerationField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("parameter", IsNullable=false)]
        public parametersParameter[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entity-generation")]
        public type_generation entitygeneration {
            get {
                return this.entitygenerationField;
            }
            set {
                this.entitygenerationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class projectsettingsDbplatforms {
        
        private projectsettingsDbplatformsDbplatform[] dbplatformField;
        
        private string selectedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("db-platform")]
        public projectsettingsDbplatformsDbplatform[] dbplatform {
            get {
                return this.dbplatformField;
            }
            set {
                this.dbplatformField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string selected {
            get {
                return this.selectedField;
            }
            set {
                this.selectedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class projectsettingsDbplatformsDbplatform {
        
        private parametersParameter[] parametersField;
        
        private projectsettingsDbplatformsDbplatformDbproviders dbprovidersField;
        
        private type_generation scriptgenerationField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("parameter", IsNullable=false)]
        public parametersParameter[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("db-providers")]
        public projectsettingsDbplatformsDbplatformDbproviders dbproviders {
            get {
                return this.dbprovidersField;
            }
            set {
                this.dbprovidersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("script-generation")]
        public type_generation scriptgeneration {
            get {
                return this.scriptgenerationField;
            }
            set {
                this.scriptgenerationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class projectsettingsDbplatformsDbplatformDbproviders {
        
        private projectsettingsDbplatformsDbplatformDbprovidersDbprovider[] dbproviderField;
        
        private string selectedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("db-provider")]
        public projectsettingsDbplatformsDbplatformDbprovidersDbprovider[] dbprovider {
            get {
                return this.dbproviderField;
            }
            set {
                this.dbproviderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string selected {
            get {
                return this.selectedField;
            }
            set {
                this.selectedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class projectsettingsDbplatformsDbplatformDbprovidersDbprovider {
        
        private parametersParameter[] parametersField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("parameter", IsNullable=false)]
        public parametersParameter[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class parameters {
        
        private parametersParameter[] parameterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameter")]
        public parametersParameter[] parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("pventitygenerator-data", Namespace="", IsNullable=false)]
    public partial class pventitygeneratordata {
        
        private projectsettings projectsettingsField;
        
        private dbdefinition dbdefinitionField;
        
        private System.DateTime generatedonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("project-settings")]
        public projectsettings projectsettings {
            get {
                return this.projectsettingsField;
            }
            set {
                this.projectsettingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("db-definition")]
        public dbdefinition dbdefinition {
            get {
                return this.dbdefinitionField;
            }
            set {
                this.dbdefinitionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("generated-on")]
        public System.DateTime generatedon {
            get {
                return this.generatedonField;
            }
            set {
                this.generatedonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("db-definition", Namespace="", IsNullable=false)]
    public partial class dbdefinition {
        
        private dbdefinitionEntity[] entitiesField;
        
        private System.DateTime generatedonField;
        
        private bool generatedonFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entity", IsNullable=false)]
        public dbdefinitionEntity[] entities {
            get {
                return this.entitiesField;
            }
            set {
                this.entitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("generated-on")]
        public System.DateTime generatedon {
            get {
                return this.generatedonField;
            }
            set {
                this.generatedonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool generatedonSpecified {
            get {
                return this.generatedonFieldSpecified;
            }
            set {
                this.generatedonFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class dbdefinitionEntity {
        
        private dbdefinitionEntityAttribute[] attributesField;
        
        private dbdefinitionEntityKeys keysField;
        
        private dbdefinitionEntityIndex[] indexesField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string hashcodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("attribute", IsNullable=false)]
        public dbdefinitionEntityAttribute[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
        
        /// <remarks/>
        public dbdefinitionEntityKeys keys {
            get {
                return this.keysField;
            }
            set {
                this.keysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("index", IsNullable=false)]
        public dbdefinitionEntityIndex[] indexes {
            get {
                return this.indexesField;
            }
            set {
                this.indexesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string hashcode {
            get {
                return this.hashcodeField;
            }
            set {
                this.hashcodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class dbdefinitionEntityAttribute {
        
        private string nameField;
        
        private type_AttributeType typeField;
        
        private bool requiredField;
        
        private string sizeField;
        
        private string scaleField;
        
        private string descriptionField;
        
        private string defaultvalueField;
        
        private bool nounittestField;
        
        private bool nounittestFieldSpecified;
        
        private bool autoincrementField;
        
        private bool autoincrementFieldSpecified;
        
        private bool deprecatedField;
        
        private bool deprecatedFieldSpecified;
        
        private string xmlmappingField;
        
        private string searchindexField;
        
        private string searchstoreField;
        
        private int searchembeddepthField;
        
        private bool searchembeddepthFieldSpecified;
        
        private float searchboostField;
        
        private bool searchboostFieldSpecified;
        
        private string searchdateresolutionField;
        
        private string searchfieldbridgeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public type_AttributeType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool required {
            get {
                return this.requiredField;
            }
            set {
                this.requiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string scale {
            get {
                return this.scaleField;
            }
            set {
                this.scaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("default-value")]
        public string defaultvalue {
            get {
                return this.defaultvalueField;
            }
            set {
                this.defaultvalueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("no-unittest")]
        public bool nounittest {
            get {
                return this.nounittestField;
            }
            set {
                this.nounittestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nounittestSpecified {
            get {
                return this.nounittestFieldSpecified;
            }
            set {
                this.nounittestFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("auto-increment")]
        public bool autoincrement {
            get {
                return this.autoincrementField;
            }
            set {
                this.autoincrementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool autoincrementSpecified {
            get {
                return this.autoincrementFieldSpecified;
            }
            set {
                this.autoincrementFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool deprecated {
            get {
                return this.deprecatedField;
            }
            set {
                this.deprecatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deprecatedSpecified {
            get {
                return this.deprecatedFieldSpecified;
            }
            set {
                this.deprecatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("xml-mapping")]
        public string xmlmapping {
            get {
                return this.xmlmappingField;
            }
            set {
                this.xmlmappingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("search-index")]
        public string searchindex {
            get {
                return this.searchindexField;
            }
            set {
                this.searchindexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("search-store")]
        public string searchstore {
            get {
                return this.searchstoreField;
            }
            set {
                this.searchstoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("search-embed-depth")]
        public int searchembeddepth {
            get {
                return this.searchembeddepthField;
            }
            set {
                this.searchembeddepthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool searchembeddepthSpecified {
            get {
                return this.searchembeddepthFieldSpecified;
            }
            set {
                this.searchembeddepthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("search-boost")]
        public float searchboost {
            get {
                return this.searchboostField;
            }
            set {
                this.searchboostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool searchboostSpecified {
            get {
                return this.searchboostFieldSpecified;
            }
            set {
                this.searchboostFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("search-date-resolution")]
        public string searchdateresolution {
            get {
                return this.searchdateresolutionField;
            }
            set {
                this.searchdateresolutionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("search-fieldbridge")]
        public string searchfieldbridge {
            get {
                return this.searchfieldbridgeField;
            }
            set {
                this.searchfieldbridgeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class dbdefinitionEntityKeys {
        
        private dbdefinitionEntityKeysPrimarykey primarykeyField;
        
        private dbdefinitionEntityKeysUniquekey[] uniquekeyField;
        
        private dbdefinitionEntityKeysForeignkey[] foreignkeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("primary-key")]
        public dbdefinitionEntityKeysPrimarykey primarykey {
            get {
                return this.primarykeyField;
            }
            set {
                this.primarykeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("unique-key")]
        public dbdefinitionEntityKeysUniquekey[] uniquekey {
            get {
                return this.uniquekeyField;
            }
            set {
                this.uniquekeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("foreign-key")]
        public dbdefinitionEntityKeysForeignkey[] foreignkey {
            get {
                return this.foreignkeyField;
            }
            set {
                this.foreignkeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class dbdefinitionEntityKeysPrimarykey {
        
        private dbdefinitionEntityKeysPrimarykeyAttributeref[] attributerefField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attribute-ref")]
        public dbdefinitionEntityKeysPrimarykeyAttributeref[] attributeref {
            get {
                return this.attributerefField;
            }
            set {
                this.attributerefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class dbdefinitionEntityKeysPrimarykeyAttributeref {
        
        private string attributeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string attribute {
            get {
                return this.attributeField;
            }
            set {
                this.attributeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class dbdefinitionEntityKeysUniquekey {
        
        private dbdefinitionEntityKeysUniquekeyAttributeref[] attributerefField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attribute-ref")]
        public dbdefinitionEntityKeysUniquekeyAttributeref[] attributeref {
            get {
                return this.attributerefField;
            }
            set {
                this.attributerefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class dbdefinitionEntityKeysUniquekeyAttributeref {
        
        private string attributeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string attribute {
            get {
                return this.attributeField;
            }
            set {
                this.attributeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class dbdefinitionEntityKeysForeignkey {
        
        private dbdefinitionEntityKeysForeignkeyAttributeref attributerefField;
        
        private string nameField;
        
        private string foreignentityField;
        
        private bool cascadingdeleteField;
        
        private bool onetooneField;
        
        public dbdefinitionEntityKeysForeignkey() {
            this.onetooneField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attribute-ref")]
        public dbdefinitionEntityKeysForeignkeyAttributeref attributeref {
            get {
                return this.attributerefField;
            }
            set {
                this.attributerefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("foreign-entity")]
        public string foreignentity {
            get {
                return this.foreignentityField;
            }
            set {
                this.foreignentityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("cascading-delete")]
        public bool cascadingdelete {
            get {
                return this.cascadingdeleteField;
            }
            set {
                this.cascadingdeleteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("one-to-one")]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool onetoone {
            get {
                return this.onetooneField;
            }
            set {
                this.onetooneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class dbdefinitionEntityKeysForeignkeyAttributeref {
        
        private string attributeField;
        
        private string foreignattributeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string attribute {
            get {
                return this.attributeField;
            }
            set {
                this.attributeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("foreign-attribute")]
        public string foreignattribute {
            get {
                return this.foreignattributeField;
            }
            set {
                this.foreignattributeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class dbdefinitionEntityIndex {
        
        private dbdefinitionEntityIndexAttributeref[] attributerefField;
        
        private string nameField;
        
        private bool uniqueField;
        
        private bool ignorenullsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attribute-ref")]
        public dbdefinitionEntityIndexAttributeref[] attributeref {
            get {
                return this.attributerefField;
            }
            set {
                this.attributerefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool unique {
            get {
                return this.uniqueField;
            }
            set {
                this.uniqueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("ignore-nulls")]
        public bool ignorenulls {
            get {
                return this.ignorenullsField;
            }
            set {
                this.ignorenullsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class dbdefinitionEntityIndexAttributeref {
        
        private string attributeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string attribute {
            get {
                return this.attributeField;
            }
            set {
                this.attributeField = value;
            }
        }
    }
}
