<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  version="1.0"
>

<xsl:import href="platform_defaults.xsl"/>

<xsl:output method="text" encoding="UTF-8"/>


<!-- ***** AllTests class generieren ***** -->
<xsl:template match="/">
<xsl:if test="$platform/parameters/parameter[@name='generate-unittest-suite']='true'">

  <!-- File Header, package, import statements -->
  <xsl:value-of select="$platform/parameters/parameter[@name='file-header']"/>
  <xsl:if test="$generate-checkstyle-suppress-comments">
    <xsl:text>//CHECKSTYLE:OFF
</xsl:text>
  </xsl:if>
  <xsl:text>
package </xsl:text><xsl:value-of select="$platform/parameters/parameter[@name='entity-unittest-package']"/><xsl:text>;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

</xsl:text>

  <!-- Class-Kommentar -->
  <xsl:if test="$generate-comments">
    <xsl:text>/**
 * Unit test suite for entity classes.
 * @author Generated by PVEntityGenerator
 */
</xsl:text>
  </xsl:if>

  <!-- Suite classes -->
  <xsl:text>
@RunWith(Suite.class)
@SuiteClasses({
</xsl:text>
  <xsl:for-each select="$db-definition/entities/entity[
        key('generate-entity', @name)//parameters/parameter[@name='generate-entity']='true'
        or key('generate-entity', @name)//parameters/parameter[@name='generate-enumeration']='true'
      ]">
    <xsl:if test="$platform/parameters/parameter[@name='generate-unittest']='true'">
      <xsl:text>  </xsl:text><xsl:value-of select="$platform/parameters/parameter[@name='entity-unittest-package']"/>
      <xsl:text>.</xsl:text><xsl:value-of select="@name"/><xsl:text>Test.class</xsl:text>
      <xsl:if test="position() &lt; last()">
        <xsl:text>,</xsl:text>
      </xsl:if>
      <xsl:text>
</xsl:text>
    </xsl:if>
  </xsl:for-each>

  <xsl:text>
</xsl:text>
  <xsl:if test="$generate-checkstyle-suppress-comments">
    <xsl:text>//CHECKSTYLE:ON
</xsl:text>
  </xsl:if>
<xsl:text>//+++ Custom class extensions START +++
// To prevent deleting your changes from PVEntityGenerator put your manual class extensions only here

//+++ Custom class extensions END +++

})
</xsl:text>

  <!-- Class Beginn -->
  <xsl:text>public class AllTests {

  // Suite class

}
</xsl:text>

</xsl:if>
</xsl:template>


</xsl:stylesheet>
